general:
  music_dirs:
    - "/Users/name/Music/"
    - "/Users/other/MP3s/"
  db:
    adapter: 'mongodb' #currently the only one
    # host: localhost
    # port: 
    database: musicbox

player:
  engine: 'raop_play' # one of raop_play, JustePort, Airfoil
  # executable: /usr/bin/raop_play (only if not in path/default location)
  ip: '10.0.100.6'
  port: 5000

indexer:
# interval in seconds (60*60*12 = 43200)
  interval: 43200
  
webapp:
  number_of_votes: 10
  port: 8080
  authentication: 
    module: ldap
