general:
  music_dirs:
    - "/Users/name/Music/"
    - "/some/other/MP3s/"
  db:
    adapter: 'mongodb' # currently the only one
    # host: localhost
    # port: 
    database: musicbox

player:
  engine: 'raop_play' # one of raop_play, juste_port, airfoil, simple_open, null (for testing and debugging)
  # executable: /usr/bin/raop_play (only if not in path/default location)
  device: '10.0.100.6'
  port: 5000
  # interval in hours during which songs can not be played again
  track_block_interval: 2 #set to 0 to disable
  # password: "airport-pw" # Only in airfoil

indexer:
# interval in hours
  interval: 12 # set to 0 to disable
  indexers:
    atomicparsley:
      executable: AtomicParsley
    mdls:
      executable: mdls
    vorbiscomment:
      executable: vorbiscomment
  types:
    ogg: vorbiscomment
    m4a: atomicparsley
    mp3: mdls
    # mp4: atomicparsley
    # m4b: atomicparsley
    # m4v: atomicparsley
  
webapp:
  number_of_votes: 10
  port: 8080
  session_secret: 'my_session_secret' #change this!
  authentication: 
    module: ldap
